name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-main:
    env:
      TEST_ES_SERVER: http://localhost:9250
      PORT: 9250
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.2', '3.3', '3.4', 'jruby-9.4', 'jruby-10' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Increase system limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: 9.0.0-SNAPSHOT
        security-enabled: false
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build
      run: |
        sudo apt-get update
        bundle install
    - name: elasticsearch-dsl
      run: bundle exec rake test:all
